FROM python-3.12

ENV GOOGLE_APPLICATION_CREDENTIALS=/home/tomas/.gc/gcp_credentials.json

RUN apt-get update && apt-get install -y python3 python3-pip
COPY requirements.txt .
RUN pip install --no-cache-dir --root-user-action=ignore -r requirements.txt

COPY export_from_bigquery_to_gcs.py .

CMD ["python", "export_from_bigquery_to_gcs.py"]
