version: 2

models:
  - name: dim_player
    description: >
      Dimension table for player information, including personal and physical details of players.

    columns:
      - name: player_id
        description: "Unique identifier for the player"
        tests:
          - not_null:
              severity: warn
          - unique:
              severity: warn

      - name: player_full_name
        description: "Full name of the player"
        tests:
          - not_null:
              severity: warn

      - name: abbrevated_name
        description: "Abbreviated name of the player (e.g., for jerseys or summaries)"

      - name: height
        description: "Height of the player"

      - name: weight
        description: "Weight of the player"

      - name: physical_stats
        description: "Raw string containing height and weight, if not separated"

      - name: player_position
        description: "Position of the player (e.g., PG, SG, C)"

      - name: player_status
        description: "Current status of the player (e.g., active, injured, out)"

      - name: birthplace_state
        description: "State where the player was born"

      - name: birthplace_country
        description: "Country where the player was born"

  - name: dim_teams
    description: >
      Dimension table for team information, including team names, aliases, conference, league, and division details.

    columns:
      - name: team_id
        description: "Unique identifier for the team"
        tests:
          - not_null:
              severity: warn
          - unique:
              severity: warn

      - name: team_name
        description: "Full name of the team"
        tests:
          - not_null:
              severity: warn

      - name: team_alias
        description: "Shortened or alternate name of the team"

      - name: team_state
        description: "State where the team is located"

      - name: conference_name
        description: "Name of the conference the team belongs to"

      - name: conference_alias
        description: "Alias or short form of the conference name"

      - name: league_name
        description: "Name of the league the team is part of"

      - name: league_alias
        description: "Alias or short form of the league name"

      - name: division_name
        description: "Name of the division the team belongs to"

      - name: division_alias
        description: "Alias or short form of the division name"

  - name: dim_tournaments
    description: "Dimension table for tournaments, with a unique surrogate key generated from season and round."
    columns:
      - name: tournament_id
        description: "Unique surrogate key for each tournament, generated from the season and round."
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
        
      - name: season
        description: "The season in which the tournament is played."
        
      - name: round
        description: "The round of the tournament."

  - name: fact_player_performance
    description: "Fact table containing player performance stats, ranks, and draft prospects based on various performance metrics."
    columns:
      - name: player_id
        description: "Unique identifier for the player."
        tests:
          - not_null:
              severity: warn

      - name: player_full_name
        description: "Full name of the player."
        
      - name: physical_stats
        description: "Physical statistics of the player (e.g., height, weight)."

      - name: player_position
        description: "Position of the player on the team."
        
      - name: player_status
        description: "Current status of the player (active, retired, etc.)."
        
      - name: birthplace_state
        description: "State where the player was born."
        
      - name: birthplace_country
        description: "Country where the player was born."

      - name: team_id
        description: "Unique identifier for the team the player belongs to."
        tests:
          - not_null:
              severity: warn

      - name: team_name
        description: "Name of the team the player belongs to."
        
      - name: team_alias
        description: "Alias or short name of the team."
        
      - name: team_state
        description: "State where the team is located."
        
      - name: conference_name
        description: "Name of the conference the team belongs to."
        
      - name: conference_alias
        description: "Alias or short name of the conference."
        
      - name: league_name
        description: "Name of the league the team belongs to."
        
      - name: league_alias
        description: "Alias or short name of the league."
        
      - name: division_name
        description: "Name of the division the team belongs to."
        
      - name: division_alias
        description: "Alias or short name of the division."
        
      - name: season
        description: "Season in which the player's performance is recorded."

      - name: total_points
        description: "Total points scored by the player in the season."
        
      - name: total_assists
        description: "Total assists made by the player in the season."
        
      - name: total_rebounds
        description: "Total rebounds made by the player in the season."
        
      - name: total_steals
        description: "Total steals made by the player in the season."
        
      - name: total_blocks
        description: "Total blocks made by the player in the season."
        
      - name: total_turnovers
        description: "Total turnovers made by the player in the season."
        
      - name: total_fouls
        description: "Total fouls committed by the player in the season."
        
      - name: total_games
        description: "Total number of games played by the player in the season."

      - name: performance_score
        description: "Calculated performance score for the player, based on various performance metrics."
        
      - name: player_rank
        description: "Rank of the player based on the performance score within their team."
        
      - name: draft_prospect
        description: "Boolean indicator for whether the player is a draft prospect (performance_score > 50)."
        tests:
          - not_null:
              severity: warn

  - name: fact_team_performance
    description: "Fact table containing team performance stats, including total and average performance metrics, and opponent team information."
    columns:
      - name: game_id
        description: "Unique identifier for the game."
        tests:
          - not_null:
              severity: warn

      - name: team_id
        description: "Unique identifier for the team."
        tests:
          - not_null:
              severity: warn

      - name: season
        description: "Season in which the game is played."

      - name: team_name
        description: "Name of the team."
        
      - name: team_alias
        description: "Alias or short name of the team."
        
      - name: team_state
        description: "State where the team is located."
        
      - name: conference_name
        description: "Name of the conference the team belongs to."
        
      - name: conference_alias
        description: "Alias or short name of the conference."
        
      - name: league_name
        description: "Name of the league the team belongs to."
        
      - name: league_alias
        description: "Alias or short name of the league."
        
      - name: division_name
        description: "Name of the division the team belongs to."
        
      - name: division_alias
        description: "Alias or short name of the division."

      - name: total_games
        description: "Total number of games played by the team in the season."
        
      - name: wins
        description: "Total number of wins by the team in the season."
        
      - name: losses
        description: "Total number of losses by the team in the season."
        
      - name: win_ratio
        description: "Win ratio of the team for the season."
        
      - name: opponents_id
        description: "Unique identifier for the opponent team."
        tests:
          - not_null:
              severity: warn

      - name: opponents_team_name
        description: "Name of the opponent team."
        
      - name: opponents_state
        description: "State where the opponent team is located."
        
      - name: opponents_alias
        description: "Alias or short name of the opponent team."

      - name: total_points
        description: "Total points scored by the team in the game."
        
      - name: total_field_goals
        description: "Total field goals made by the team in the game."
        
      - name: total_free_throws_made
        description: "Total free throws made by the team in the game."
        
      - name: total_assists
        description: "Total assists made by the team in the game."
        
      - name: total_rebounds
        description: "Total rebounds made by the team in the game."
        
      - name: total_defensive_rebounds
        description: "Total defensive rebounds made by the team in the game."
        
      - name: total_offensive_rebounds
        description: "Total offensive rebounds made by the team in the game."
        
      - name: total_blocks
        description: "Total blocks made by the team in the game."
        
      - name: total_steals
        description: "Total steals made by the team in the game."
        
      - name: total_turnovers
        description: "Total turnovers made by the team in the game."
        
      - name: avg_points_per_game
        description: "Average points scored per game by the team."
        
      - name: avg_assists_per_game
        description: "Average assists per game by the team."
        
      - name: avg_field_goals_percentage
        description: "Average field goal percentage for the team."
        
      - name: avg_two_points_percentage
        description: "Average two-point field goal percentage for the team."
        
      - name: avg_three_points_percentage
        description: "Average three-point field goal percentage for the team."
        
      - name: avg_free_throws_percentage
        description: "Average free throw percentage for the team."

  - name: fact_tournament_game_performance
    description: "Fact table containing tournament game performance details, including teams, points, and the outcome of games."
    columns:
      - name: tournament_game_id
        description: "Unique identifier for each tournament game."
        tests:
          - not_null:
              severity: warn

      - name: season
        description: "Season in which the tournament game was played."

      - name: round
        description: "Round of the tournament (e.g., 1st round, semi-finals, finals)."

      - name: win_team_id
        description: "Unique identifier of the winning team."
        tests:
          - not_null:
              severity: warn

      - name: winning_team
        description: "Name of the winning team."

      - name: winning_team_points
        description: "Points scored by the winning team in the game."

      - name: lose_team_id
        description: "Unique identifier of the losing team."
        tests:
          - not_null:
              severity: warn

      - name: losing_team
        description: "Name of the losing team."

      - name: losing_team_points
        description: "Points scored by the losing team in the game."

      - name: point_difference
        description: "The difference in points between the winning and losing team."


